<a href="https://colab.research.google.com/github/19PA1A0261/AI-Lab/blob/master/Exp_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 # "Experiment No 1:Numpy"

##i)Different ways to create Numpy arrays

In [ ]:
import numpy as np
x = np. array([4,5,6])
print(x)

[4 5 6]


In [ ]:
x = np. array ([[4,5,6],[40,50,60]])
print(x)

[[ 4  5  6]
 [40 50 60]]


 ## ii)add,remove,modify elements in array

###Add

In [ ]:
x = np. array([4,5,6])
y = np. append(x,[88,89,90])
print(y)

[ 4  5  6 88 89 90]


 ### Remove

In [ ]:
x = np .delete(x,2)
print(x)

[4 5]


### Modify

In [ ]:
x[x<5]=-1
print(x)

[-1  5]


## iii)Arithmetic operations on Numpy array

In [ ]:
import numpy as np 
x = ([6,5,4])
y = ([4,5,6])
num_sum = np.add(x,y)
num_diff = np.subtract(x,y)
num_quo = np.divide(x,y)
num_mod = np.mod(x,y)
num_pow = np.power(x,y)
print(num_sum)
print(num_diff)
print(num_quo)
print(num_mod)
print(num_pow)

[10 10 10]
[ 2  0 -2]
[1.5        1.         0.66666667]
[2 0 4]
[1296 3125 4096]


## iv) Slicing and iterating of Numpy arrays

### Slicing

In [ ]:
import numpy as np 
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:10])

[ 2  3  4  5  6  7  8  9 10]


 ### Iterating

In [ ]:
for x in arr:
  print(x)

1
2
3
4
5
6
7
8
9
10


## V)Matrix operations on Numpy arrays

In [ ]:
import numpy as np 
x = np. array([[4,5],[6,7]])
y = np. array([[40,50],[60,70]])
print(np.add(x,y))
print(np.subtract(x,y))
print(np.divide(x,y))

[[44 55]
 [66 77]]
[[-36 -45]
 [-54 -63]]
[[0.1 0.1]
 [0.1 0.1]]
